### PR TITLE
Changed pin/unpin icon for tertiary navigation

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by skateman** [comment]
@epwinchell review please

**Comment by epwinchell** [comment]
@miq-bot add_label ui, bug

**Comment by epwinchell** [comment]
@miq-bot assign @dclarizio

**Comment by epwinchell** [comment]
@skateman code looks fine. How do I test this?

**Comment by skateman** [comment]
Change the `patternfly-sass` line in `Gemfile` to: 

``` ruby
gem 'patternfly-sass', :github => 'skateman/patternfly-sass', :branch => 'tertiary-nav'
```

Then run a `bundle update`.

**Comment by epwinchell** [comment]
@skateman Tested. Please merge.

**Comment by skateman** [comment]
@simaishi just making sure, do I need to do anything extra after merge to have this [in Darga](https://github.com/ManageIQ/manageiq/blob/darga/Gemfile#L28)?

**Comment by skateman** [comment]
Travis had some issues with this PR, reopening it as #4!

**Pull request merged**
